### ISSUE TITLE
update database from google spreadsheet

### ISSUE THREAD

**Issue by beccasjames** [sunlightlabs/hall-of-justice#33]
If it hasn't been done recently (or isn't run automatically/on a regular basis yet) please update the database from the [spreadsheet](https://docs.google.com/spreadsheets/d/1-_9odW05pc74haHvfdlSIqot_cyEzA9MGUZ5mppm7cM/edit#gid=320968707)

**Comment by crdunwel** [comment]
As simple as this sounds, it's actually a pain in the ass to do programmatically because of how permissions work with google drive. Would it be okay to handle this manually for the time being? Seems being a week or so behind the source for an alpha version is reasonable.

**Comment by beccasjames** [comment]
Of course. Just so we're aware, how often is the HOJ database updated, or is it not done automatically?

**Comment by crdunwel** [comment]
As far as I know, it's not done automatically at this time. Cloud was just downloading the google sheet file manually as a .xls file and rebuilding the database as needed.

**Comment by crdunwel** [comment]
@beccasjames 
https://github.com/sunlightlabs/hall-of-justice/commit/c63a684d69747e54b0f05e2e24fcee236c6c9b43 fixes problems with most recent code and data should be up to date. Let me know if things look good and we can close this. I made a change so that the top level categories also display all entries with child subcategories in the list view. Can revert this easily if that's not desirable behavior.

**Comment by beccasjames** [comment]
This looks really great -- export data feature is tops.  Would it be possible to add back in the parent categories to the list/table view? I think that extra level of organization will help other who are less familiar with the schema find what they're looking for.

**Comment by crdunwel** [comment]
Yep. Added back in https://github.com/sunlightlabs/hall-of-justice/commit/f9ffe5f879458f8dfb3f02ce49dd68f720c724c8 . If things look good then close this issue por favor.
